name: 'neuronews'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'neuronews'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  neuronews:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
      +file_format: iceberg
      +table_type: iceberg

# Global configurations for Iceberg tables
vars:
  # Iceberg table properties
  iceberg_table_properties:
    'write.format.default': 'parquet'
    'write.parquet.compression-codec': 'snappy'
    'write.metadata.compression-codec': 'gzip'
    'history.expire.max-snapshot-age-ms': '432000000'  # 5 days
    'history.expire.min-snapshots-to-keep': '5'

# Test configurations
tests:
  +store_failures: true
  +severity: warn

# Documentation
docs:
  generate: true

# Seeds configuration
seeds:
  neuronews:
    +schema: seeds
    +file_format: iceberg
