apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-finops-budget-alerts
  namespace: monitoring
  labels:
    app: prometheus
    component: alerting-rules
    purpose: finops-budget-monitoring
data:
  finops_budget_alerts.yml: |
    groups:
    - name: finops-budget-alerts
      interval: 30s
      rules:
      
      # =============================================================================
      # Monthly Budget Projection Alerts
      # =============================================================================
      
      # Alert when projected monthly cost exceeds budget
      - alert: FinOpsMonthlyBudgetBreach
        expr: |
          (
            sum(opencost_node_cost_hourly) * 24 * 30
          ) > on() group_left() (
            scalar(prometheus_config_last_reload_successful) * 0 + ${BUDGET_EUR:5000}
          )
        for: 30m
        labels:
          severity: warning
          team: platform
          category: finops
          impact: budget
        annotations:
          summary: "Projected monthly cost exceeds budget"
          description: |
            Current hourly cost rate projects to €{{ $value | humanize }} per month,
            which exceeds the configured budget of €${BUDGET_EUR:5000}.
            
            Current hourly rate: €{{ with query "sum(opencost_node_cost_hourly)" }}{{ . | first | value | printf "%.2f" }}{{ end }}
            Daily projection: €{{ with query "sum(opencost_node_cost_hourly) * 24" }}{{ . | first | value | printf "%.2f" }}{{ end }}
            Monthly projection: €{{ $value | printf "%.2f" }}
            Budget: €${BUDGET_EUR:5000}
            Overage: €{{ with query "sum(opencost_node_cost_hourly) * 24 * 30 - ${BUDGET_EUR:5000}" }}{{ . | first | value | printf "%.2f" }}{{ end }}
          runbook_url: "https://github.com/Ikey168/NeuroNews/blob/main/docs/runbooks/finops-budget-alerts.md"
          grafana_url: "http://grafana.monitoring.svc.cluster.local:3000/d/unit-economics-001/unit-economics-cost-per-outcome"
      
      # Critical alert when projected cost is significantly over budget (>150%)
      - alert: FinOpsMonthlyBudgetCriticalBreach
        expr: |
          (
            sum(opencost_node_cost_hourly) * 24 * 30
          ) > on() group_left() (
            scalar(prometheus_config_last_reload_successful) * 0 + ${BUDGET_EUR:5000} * 1.5
          )
        for: 15m
        labels:
          severity: critical
          team: platform
          category: finops
          impact: budget
        annotations:
          summary: "CRITICAL: Monthly cost projection 50%+ over budget"
          description: |
            Current hourly cost rate projects to €{{ $value | humanize }} per month,
            which is >150% of the configured budget (€${BUDGET_EUR:5000}).
            Immediate cost optimization required.
            
            Current hourly rate: €{{ with query "sum(opencost_node_cost_hourly)" }}{{ . | first | value | printf "%.2f" }}{{ end }}
            Monthly projection: €{{ $value | printf "%.2f" }}
            Budget: €${BUDGET_EUR:5000}
            Critical threshold: €{{ with query "${BUDGET_EUR:5000} * 1.5" }}{{ . | first | value | printf "%.2f" }}{{ end }}
            Overage: €{{ with query "sum(opencost_node_cost_hourly) * 24 * 30 - ${BUDGET_EUR:5000}" }}{{ . | first | value | printf "%.2f" }}{{ end }}
          runbook_url: "https://github.com/Ikey168/NeuroNews/blob/main/docs/runbooks/finops-budget-alerts.md"
      
      # =============================================================================
      # Week-over-Week Cost Drift Alerts
      # =============================================================================
      
      # Alert on significant week-over-week cost increase (>=30%)
      - alert: FinOpsCostDriftWoW
        expr: |
          (
            (
              sum_over_time(opencost_node_cost_hourly[7d]) - 
              sum_over_time(opencost_node_cost_hourly offset 7d [7d])
            ) / sum_over_time(opencost_node_cost_hourly offset 7d [7d])
          ) > 0.3
        for: 1h
        labels:
          severity: warning
          team: platform
          category: finops
          impact: cost-drift
        annotations:
          summary: "Significant week-over-week cost increase detected"
          description: |
            Infrastructure costs have increased by {{ $value | humanizePercentage }} 
            compared to the same period last week.
            
            This week total: €{{ with query "sum_over_time(opencost_node_cost_hourly[7d])" }}{{ . | first | value | printf "%.2f" }}{{ end }}
            Last week total: €{{ with query "sum_over_time(opencost_node_cost_hourly offset 7d [7d])" }}{{ . | first | value | printf "%.2f" }}{{ end }}
            Increase: {{ $value | humanizePercentage }}
            
            Check for:
            - New deployments or scaling events
            - Resource configuration changes
            - Workload pattern changes
          runbook_url: "https://github.com/Ikey168/NeuroNews/blob/main/docs/runbooks/finops-cost-drift.md"
          grafana_url: "http://grafana.monitoring.svc.cluster.local:3000/d/neuronews-finops/neuronews-finops"
      
      # Critical alert for extreme cost drift (>=100% increase)
      - alert: FinOpsCostDriftCritical
        expr: |
          (
            (
              sum_over_time(opencost_node_cost_hourly[7d]) - 
              sum_over_time(opencost_node_cost_hourly offset 7d [7d])
            ) / sum_over_time(opencost_node_cost_hourly offset 7d [7d])
          ) > 1.0
        for: 30m
        labels:
          severity: critical
          team: platform
          category: finops
          impact: cost-drift
        annotations:
          summary: "CRITICAL: Infrastructure costs doubled week-over-week"
          description: |
            Infrastructure costs have more than doubled ({{ $value | humanizePercentage }} increase)
            compared to last week. Immediate investigation required.
            
            This week total: €{{ with query "sum_over_time(opencost_node_cost_hourly[7d])" }}{{ . | first | value | printf "%.2f" }}{{ end }}
            Last week total: €{{ with query "sum_over_time(opencost_node_cost_hourly offset 7d [7d])" }}{{ . | first | value | printf "%.2f" }}{{ end }}
            Increase: {{ $value | humanizePercentage }}
          runbook_url: "https://github.com/Ikey168/NeuroNews/blob/main/docs/runbooks/finops-cost-drift.md"
      
      # =============================================================================
      # Daily Budget Burn Rate Alerts
      # =============================================================================
      
      # Alert when daily spend exceeds expected budget allocation
      - alert: FinOpsDailyBudgetBurnRate
        expr: |
          (
            sum_over_time(opencost_node_cost_hourly[24h])
          ) > on() group_left() (
            scalar(prometheus_config_last_reload_successful) * 0 + ${BUDGET_EUR:5000} / 30
          )
        for: 2h
        labels:
          severity: warning
          team: platform
          category: finops
          impact: budget
        annotations:
          summary: "Daily spend exceeds budget allocation"
          description: |
            Daily infrastructure cost (€{{ $value | printf "%.2f" }}) exceeds 
            the daily budget allocation (€{{ with query "${BUDGET_EUR:5000} / 30" }}{{ . | first | value | printf "%.2f" }}{{ end }}).
            
            Daily actual: €{{ $value | printf "%.2f" }}
            Daily budget: €{{ with query "${BUDGET_EUR:5000} / 30" }}{{ . | first | value | printf "%.2f" }}{{ end }}
            Monthly budget: €${BUDGET_EUR:5000}
            Projected monthly (at current rate): €{{ with query "sum_over_time(opencost_node_cost_hourly[24h]) * 30" }}{{ . | first | value | printf "%.2f" }}{{ end }}
          grafana_url: "http://grafana.monitoring.svc.cluster.local:3000/d/unit-economics-001/unit-economics-cost-per-outcome"
      
      # =============================================================================
      # Unit Economics Alerts
      # =============================================================================
      
      # Alert when cost per 1k articles exceeds threshold
      - alert: FinOpsUnitEconomicsArticles
        expr: |
          unit_economics:cost_per_1k_articles_hourly > ${COST_PER_1K_ARTICLES_THRESHOLD:2.0}
        for: 1h
        labels:
          severity: warning
          team: data-engineering
          category: finops
          impact: unit-economics
        annotations:
          summary: "Cost per 1k articles exceeds threshold"
          description: |
            Current cost per 1000 articles (€{{ $value | printf "%.2f" }}) exceeds 
            the configured threshold (€${COST_PER_1K_ARTICLES_THRESHOLD:2.0}).
            
            Current cost/1k articles: €{{ $value | printf "%.2f" }}
            Threshold: €${COST_PER_1K_ARTICLES_THRESHOLD:2.0}
            Articles/hour: {{ with query "articles:rate_1h" }}{{ . | first | value | printf "%.0f" }}{{ end }}
            Hourly cost: €{{ with query "cost:cluster_hourly:sum" }}{{ . | first | value | printf "%.2f" }}{{ end }}
          runbook_url: "https://github.com/Ikey168/NeuroNews/blob/main/docs/runbooks/unit-economics-optimization.md"
      
      # Alert when cost per RAG query exceeds threshold
      - alert: FinOpsUnitEconomicsRAGQueries
        expr: |
          unit_economics:cost_per_rag_query_hourly > ${COST_PER_RAG_QUERY_THRESHOLD:0.05}
        for: 1h
        labels:
          severity: warning
          team: data-engineering
          category: finops
          impact: unit-economics
        annotations:
          summary: "Cost per RAG query exceeds threshold"
          description: |
            Current cost per RAG query (€{{ $value | printf "%.4f" }}) exceeds 
            the configured threshold (€${COST_PER_RAG_QUERY_THRESHOLD:0.05}).
            
            Current cost/query: €{{ $value | printf "%.4f" }}
            Threshold: €${COST_PER_RAG_QUERY_THRESHOLD:0.05}
            Queries/hour: {{ with query "ragq:rate_1h" }}{{ . | first | value | printf "%.0f" }}{{ end }}
            Hourly cost: €{{ with query "cost:cluster_hourly:sum" }}{{ . | first | value | printf "%.2f" }}{{ end }}
          runbook_url: "https://github.com/Ikey168/NeuroNews/blob/main/docs/runbooks/unit-economics-optimization.md"
      
      # =============================================================================
      # Resource Efficiency Alerts
      # =============================================================================
      
      # Alert on low resource efficiency (high cost per business outcome)
      - alert: FinOpsLowResourceEfficiency
        expr: |
          (
            efficiency:articles_per_euro_hourly < 100 
            or 
            efficiency:queries_per_euro_hourly < 20
          ) and on() (
            articles:rate_1h > 10 or ragq:rate_1h > 5
          )
        for: 2h
        labels:
          severity: warning
          team: platform
          category: finops
          impact: efficiency
        annotations:
          summary: "Low resource efficiency detected"
          description: |
            Infrastructure efficiency is below expected thresholds while processing significant load.
            
            Articles per €: {{ with query "efficiency:articles_per_euro_hourly" }}{{ . | first | value | printf "%.0f" }}{{ end }} (threshold: 100)
            Queries per €: {{ with query "efficiency:queries_per_euro_hourly" }}{{ . | first | value | printf "%.0f" }}{{ end }} (threshold: 20)
            
            Current load:
            - Articles/hour: {{ with query "articles:rate_1h" }}{{ . | first | value | printf "%.0f" }}{{ end }}
            - Queries/hour: {{ with query "ragq:rate_1h" }}{{ . | first | value | printf "%.0f" }}{{ end }}
            - Hourly cost: €{{ with query "cost:cluster_hourly:sum" }}{{ . | first | value | printf "%.2f" }}{{ end }}
          runbook_url: "https://github.com/Ikey168/NeuroNews/blob/main/docs/runbooks/resource-efficiency-optimization.md"
