apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: data-contracts-alerts
  namespace: neuronews
  labels:
    app: neuronews
    component: data-contracts
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
  - name: data-contracts.rules
    interval: 30s
    rules:
    
    # ===========================================================================
    # Contract Validation Failure Rate Alerts
    # ===========================================================================
    
    - alert: ContractValidationFailureRateHigh
      expr: |
        (
          rate(contracts_validation_fail_total[15m]) /
          (rate(contracts_validation_fail_total[15m]) + rate(contracts_validation_success_total[15m]))
        ) * 100 > 1
      for: 5m
      labels:
        severity: warning
        component: data-contracts
        team: data-platform
      annotations:
        summary: "High contract validation failure rate detected"
        description: |
          Contract validation failure rate is {{ printf "%.2f" $value }}% over the last 15 minutes
          for pipeline {{ $labels.pipeline }} and source {{ $labels.source_id }}.
          This exceeds the 1% threshold and may indicate data quality issues.
        runbook_url: "https://docs.neuronews.com/runbooks/contract-validation-failures"
        dashboard_url: "https://grafana.neuronews.com/d/contracts/data-contracts-dashboard"
    
    - alert: ContractValidationFailureRateCritical
      expr: |
        (
          rate(contracts_validation_fail_total[15m]) /
          (rate(contracts_validation_fail_total[15m]) + rate(contracts_validation_success_total[15m]))
        ) * 100 > 5
      for: 2m
      labels:
        severity: critical
        component: data-contracts
        team: data-platform
      annotations:
        summary: "Critical contract validation failure rate detected"
        description: |
          Contract validation failure rate is {{ printf "%.2f" $value }}% over the last 15 minutes
          for pipeline {{ $labels.pipeline }} and source {{ $labels.source_id }}.
          This exceeds the 5% critical threshold and requires immediate attention.
        runbook_url: "https://docs.neuronews.com/runbooks/contract-validation-failures"
        dashboard_url: "https://grafana.neuronews.com/d/contracts/data-contracts-dashboard"
    
    # ===========================================================================
    # Breaking Change Detection Alerts
    # ===========================================================================
    
    - alert: ContractBreakingChangeDetected
      expr: increase(contracts_breaking_change_total[5m]) > 0
      for: 0m
      labels:
        severity: critical
        component: data-contracts
        team: data-platform
      annotations:
        summary: "Breaking change detected in data contract"
        description: |
          A breaking change has been detected in schema {{ $labels.schema_name }}
          for pipeline {{ $labels.pipeline }}. Change type: {{ $labels.change_type }}.
          Detection source: {{ $labels.detection_source }}.
          Immediate action required to prevent data pipeline failures.
        runbook_url: "https://docs.neuronews.com/runbooks/breaking-changes"
        dashboard_url: "https://grafana.neuronews.com/d/contracts/data-contracts-dashboard"
    
    - alert: ContractBreakingChangeInCI
      expr: increase(contracts_breaking_change_total{detection_source="ci"}[5m]) > 0
      for: 0m
      labels:
        severity: warning
        component: data-contracts
        team: data-platform
      annotations:
        summary: "Breaking change detected in CI pipeline"
        description: |
          A breaking change has been detected in CI for schema {{ $labels.schema_name }}
          in pipeline {{ $labels.pipeline }}. Change type: {{ $labels.change_type }}.
          This change should be reviewed before deployment.
        runbook_url: "https://docs.neuronews.com/runbooks/ci-breaking-changes"
        dashboard_url: "https://grafana.neuronews.com/d/contracts/data-contracts-dashboard"
    
    # ===========================================================================
    # Dead Letter Queue Alerts
    # ===========================================================================
    
    - alert: ContractDLQRateHigh
      expr: rate(contracts_dlq_total[15m]) > 10
      for: 5m
      labels:
        severity: warning
        component: data-contracts
        team: data-platform
      annotations:
        summary: "High rate of messages sent to dead letter queue"
        description: |
          {{ printf "%.2f" $value }} messages per second are being sent to the dead letter queue
          for pipeline {{ $labels.pipeline }} and source {{ $labels.source_id }}.
          Reason: {{ $labels.reason }}. This may indicate systemic validation issues.
        runbook_url: "https://docs.neuronews.com/runbooks/dlq-investigation"
        dashboard_url: "https://grafana.neuronews.com/d/contracts/data-contracts-dashboard"
    
    # ===========================================================================
    # Contract Validation Latency Alerts
    # ===========================================================================
    
    - alert: ContractValidationLatencyHigh
      expr: histogram_quantile(0.95, rate(contracts_validation_latency_ms_bucket[5m])) > 1000
      for: 10m
      labels:
        severity: warning
        component: data-contracts
        team: data-platform
      annotations:
        summary: "High contract validation latency detected"
        description: |
          95th percentile contract validation latency is {{ printf "%.2f" $value }}ms
          for pipeline {{ $labels.pipeline }} and schema {{ $labels.schema_name }}.
          This may impact data processing throughput.
        runbook_url: "https://docs.neuronews.com/runbooks/validation-latency"
        dashboard_url: "https://grafana.neuronews.com/d/contracts/data-contracts-dashboard"
    
    # ===========================================================================
    # Schema Registry Health Alerts
    # ===========================================================================
    
    - alert: SchemaCompatibilityChecksFailing
      expr: rate(contracts_compatibility_check_total{result="error"}[15m]) > 0.1
      for: 5m
      labels:
        severity: warning
        component: data-contracts
        team: data-platform
      annotations:
        summary: "Schema compatibility checks are failing"
        description: |
          Schema compatibility checks are failing at a rate of {{ printf "%.2f" $value }} per second
          for schema {{ $labels.schema_name }}. This may indicate issues with the schema registry
          or incompatible schema changes.
        runbook_url: "https://docs.neuronews.com/runbooks/schema-registry-issues"
        dashboard_url: "https://grafana.neuronews.com/d/contracts/data-contracts-dashboard"
    
    # ===========================================================================
    # Recording Rules for Aggregated Metrics
    # ===========================================================================
    
    - record: contracts:validation_failure_rate_5m
      expr: |
        rate(contracts_validation_fail_total[5m]) /
        (rate(contracts_validation_fail_total[5m]) + rate(contracts_validation_success_total[5m])) * 100
    
    - record: contracts:validation_failure_rate_15m
      expr: |
        rate(contracts_validation_fail_total[15m]) /
        (rate(contracts_validation_fail_total[15m]) + rate(contracts_validation_success_total[15m])) * 100
    
    - record: contracts:breaking_changes_per_hour
      expr: increase(contracts_breaking_change_total[1h])
    
    - record: contracts:dlq_rate_5m
      expr: rate(contracts_dlq_total[5m])
    
    - record: contracts:validation_latency_p95_5m
      expr: histogram_quantile(0.95, rate(contracts_validation_latency_ms_bucket[5m]))
    
    - record: contracts:validation_latency_p99_5m
      expr: histogram_quantile(0.99, rate(contracts_validation_latency_ms_bucket[5m]))
