[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "neuronews"
version = "0.1.0"
authors = [
  { name="Your Name", email="your.email@example.com" },
]
description = "A system for scraping and analyzing news articles"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "boto3>=1.26.0",
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0"
]

[project.urls]
"Homepage" = "https://github.com/yourusername/neuronews"
"Bug Tracker" = "https://github.com/yourusername/neuronews/issues"

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = """
    -v 
    --cov=src 
    --cov-report=term-missing 
    --cov-report=html:coverage_report 
    --cov-branch
"""

[tool.hatch.build.targets.wheel]
packages = ["src"]