apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-topics-config
  namespace: neuronews
  labels:
    app: kafka
    component: topics
data:
  create-topics.sh: |
    #!/bin/bash
    set -e
    
    # Wait for Kafka to be ready
    echo "Waiting for Kafka to be ready..."
    until kafka-topics.sh --bootstrap-server kafka:9092 --list > /dev/null 2>&1; do
      echo "Kafka not ready, waiting..."
      sleep 5
    done
    
    echo "Kafka is ready. Creating topics..."
    
    # Create main article ingest topic
    kafka-topics.sh --bootstrap-server kafka:9092 \
      --create \
      --topic article_ingest \
      --partitions 3 \
      --replication-factor 1 \
      --if-not-exists \
      --config cleanup.policy=compact \
      --config retention.ms=604800000
    
    # Create DLQ topic for invalid messages  
    kafka-topics.sh --bootstrap-server kafka:9092 \
      --create \
      --topic article_ingest_dlq \
      --partitions 3 \
      --replication-factor 1 \
      --if-not-exists \
      --config cleanup.policy=delete \
      --config retention.ms=2592000000
    
    echo "Topics created successfully:"
    kafka-topics.sh --bootstrap-server kafka:9092 --list
    
    # Show topic details
    echo "Topic details:"
    kafka-topics.sh --bootstrap-server kafka:9092 --describe --topic article_ingest
    kafka-topics.sh --bootstrap-server kafka:9092 --describe --topic article_ingest_dlq

---
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topics-creator
  namespace: neuronews
  labels:
    app: kafka
    component: topic-creator
spec:
  template:
    metadata:
      labels:
        app: kafka
        component: topic-creator
    spec:
      restartPolicy: OnFailure
      containers:
      - name: kafka-topics-creator
        image: confluentinc/cp-kafka:7.4.0
        command: ["/bin/bash"]
        args: ["/config/create-topics.sh"]
        volumeMounts:
        - name: topics-config
          mountPath: /config
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
      volumes:
      - name: topics-config
        configMap:
          name: kafka-topics-config
          defaultMode: 0755
