apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer-service
  namespace: neuronews
  labels:
    app: nginx-load-balancer
    component: load-balancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: nginx-load-balancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer-internal
  namespace: neuronews
  labels:
    app: nginx-load-balancer
    component: load-balancer
    service-type: internal
spec:
  type: ClusterIP
  selector:
    app: nginx-load-balancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
