apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-ingest-consumer
  namespace: neuronews
  labels:
    app: article-ingest-consumer
    component: consumer
    tier: ingestion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: article-ingest-consumer
  template:
    metadata:
      labels:
        app: article-ingest-consumer
        component: consumer
        tier: ingestion
    spec:
      containers:
      - name: consumer
        image: neuronews/article-ingest-consumer:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: CONSUMER_GROUP
          value: "article-ingest-consumer"
        - name: TOPIC
          value: "article_ingest"
        - name: DLQ_TOPIC
          value: "article_ingest_dlq"
        - name: SCHEMA_REGISTRY_URL
          value: "http://schema-registry:8081"
        - name: LOG_LEVEL
          value: "INFO"
        - name: MAX_POLL_RECORDS
          value: "100"
        - name: ENABLE_VALIDATION
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: article-ingest-consumer-service
  namespace: neuronews
  labels:
    app: article-ingest-consumer
spec:
  selector:
    app: article-ingest-consumer
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: article-ingest-consumer-metrics
  namespace: neuronews
  labels:
    app: article-ingest-consumer
spec:
  selector:
    matchLabels:
      app: article-ingest-consumer
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
