version: 2

models:
  - name: stg_articles_raw
    description: "Staging view for raw articles with basic cleaning and standardization"
    columns:
      - name: article_id
        description: "Unique article identifier"
        tests:
          - not_null
          - unique
      - name: title
        description: "Cleaned article title"
        tests:
          - not_null
      - name: content
        description: "Cleaned article content"
      - name: source
        description: "Standardized news source"
        tests:
          - not_null
      - name: published_at
        description: "Article publication timestamp"
        tests:
          - not_null
      - name: is_valid_row
        description: "Data quality indicator"

  - name: stg_articles_enriched
    description: "Staging view for enriched articles with NLP analytics"
    columns:
      - name: article_id
        description: "Unique article identifier"
        tests:
          - not_null
          - unique
      - name: sentiment_score
        description: "Sentiment analysis score"
      - name: sentiment_label
        description: "Sentiment classification"
      - name: content_quality_score
        description: "Content quality metric"
      - name: is_fully_enriched
        description: "Enrichment completeness indicator"

  - name: fact_articles
    description: "Main fact table combining raw and enriched article data"
    columns:
      - name: article_id
        description: "Unique article identifier"
        tests:
          - not_null
          - unique
      - name: title
        description: "Article title"
        tests:
          - not_null
      - name: source
        description: "News source"
        tests:
          - not_null
      - name: published_at
        description: "Publication timestamp"
        tests:
          - not_null
      - name: sentiment_score
        description: "Sentiment analysis score (-1 to 1)"
        tests:
          - not_null
      - name: content_quality_score
        description: "Content quality score (0 to 1)"
        tests:
          - not_null
      - name: is_valid_row
        description: "Data quality flag"
        tests:
          - not_null

  - name: dim_sources
    description: "Source dimension with aggregated metrics"
    columns:
      - name: source
        description: "News source identifier"
        tests:
          - not_null
      - name: total_articles
        description: "Total article count"
        tests:
          - not_null
      - name: avg_content_quality
        description: "Average content quality score"
      - name: enrichment_rate
        description: "Percentage of enriched articles"

  - name: agg_daily_metrics
    description: "Daily aggregated metrics for trend analysis"
    columns:
      - name: published_date
        description: "Publication date"
        tests:
          - not_null
          - unique
      - name: total_articles
        description: "Daily article count"
        tests:
          - not_null
      - name: avg_sentiment_score
        description: "Average daily sentiment"
      - name: enrichment_rate
        description: "Daily enrichment rate"
