apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-finops
  namespace: monitoring
  labels:
    app: grafana
    component: dashboards
    category: finops
data:
  neuronews-finops.json: |
    {{ .Files.Get "dashboards/neuronews-finops.json" | nindent 4 }}
  opencost-overview.json: |
    {{ .Files.Get "dashboards/opencost-overview.json" | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provisioning
  namespace: monitoring
  labels:
    app: grafana
    component: provisioning
data:
  finops.yaml: |
    apiVersion: 1
    providers:
      - name: "NeuroNews FinOps Dashboards"
        orgId: 1
        folder: "FinOps"
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/finops
      
      - name: "OpenCost Dashboards"
        orgId: 1
        folder: "OpenCost"
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/opencost

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-opencost
  namespace: monitoring
  labels:
    app: grafana
    component: datasources
data:
  opencost.yaml: |
    apiVersion: 1
    datasources:
      - name: OpenCost
        type: prometheus
        access: proxy
        orgId: 1
        url: http://opencost.opencost.svc.cluster.local:9003
        isDefault: false
        version: 1
        editable: true
        jsonData:
          httpMethod: POST
          queryTimeout: 300s
          timeInterval: 30s
          customQueryParameters: "format=prometheus"
