version: 2

semantic_models:
  - name: sources
    description: "Publisher/source attributes."
    model: ref('sources_sample')   # using sample model for testing
    entities:
      - name: source
        type: primary
        expr: source_id
    dimensions:
      - name: source_name
        type: categorical
      - name: category
        type: categorical
      - name: country
        type: categorical
        expr: country_code
