apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: finops-labels-overlay

resources:
- ../../k8s/deployments/
- ../../spark/

patchesStrategicMerge:
- patches/kafka-labels.yaml
- patches/spark-labels.yaml  
- patches/api-labels.yaml
- patches/monitoring-labels.yaml

patches:
# Patch all Deployments in neuronews namespace
- target:
    group: apps
    version: v1
    kind: Deployment
    namespace: neuronews
  patch: |-
    - op: add
      path: /metadata/labels/pipeline
      value: api
    - op: add
      path: /metadata/labels/team
      value: neuronews
    - op: add
      path: /metadata/labels/env
      value: prod
    - op: add
      path: /metadata/labels/cost_center
      value: product
    - op: add
      path: /spec/template/metadata/labels/pipeline
      value: api
    - op: add
      path: /spec/template/metadata/labels/team
      value: neuronews
    - op: add
      path: /spec/template/metadata/labels/env
      value: prod
    - op: add
      path: /spec/template/metadata/labels/cost_center
      value: product

# Patch all StatefulSets in data-processing namespace  
- target:
    group: apps
    version: v1
    kind: StatefulSet
    namespace: data-processing
  patch: |-
    - op: add
      path: /metadata/labels/pipeline
      value: ingest
    - op: add
      path: /metadata/labels/team
      value: data-engineering
    - op: add
      path: /metadata/labels/env
      value: prod
    - op: add
      path: /metadata/labels/cost_center
      value: data-platform
    - op: add
      path: /spec/template/metadata/labels/pipeline
      value: ingest
    - op: add
      path: /spec/template/metadata/labels/team
      value: data-engineering
    - op: add
      path: /spec/template/metadata/labels/env
      value: prod
    - op: add
      path: /spec/template/metadata/labels/cost_center
      value: data-platform

# Patch Jobs in data-processing namespace
- target:
    group: batch
    version: v1
    kind: Job
    namespace: data-processing
  patch: |-
    - op: add
      path: /metadata/labels/pipeline
      value: transform
    - op: add
      path: /metadata/labels/team
      value: data-engineering
    - op: add
      path: /metadata/labels/env
      value: prod
    - op: add
      path: /metadata/labels/cost_center
      value: data-platform
    - op: add
      path: /spec/template/metadata/labels/pipeline
      value: transform
    - op: add
      path: /spec/template/metadata/labels/team
      value: data-engineering
    - op: add
      path: /spec/template/metadata/labels/env
      value: prod
    - op: add
      path: /spec/template/metadata/labels/cost_center
      value: data-platform

# Patch monitoring workloads
- target:
    group: apps
    version: v1
    kind: Deployment
    namespace: monitoring
  patch: |-
    - op: add
      path: /metadata/labels/pipeline
      value: monitoring
    - op: add
      path: /metadata/labels/team
      value: platform
    - op: add
      path: /metadata/labels/env
      value: prod
    - op: add
      path: /metadata/labels/cost_center
      value: infrastructure
    - op: add
      path: /spec/template/metadata/labels/pipeline
      value: monitoring
    - op: add
      path: /spec/template/metadata/labels/team
      value: platform
    - op: add
      path: /spec/template/metadata/labels/env
      value: prod
    - op: add
      path: /spec/template/metadata/labels/cost_center
      value: infrastructure
