apiVersion: v1
kind: ConfigMap
metadata:
  name: finops-labeling-schema
  namespace: kube-system
  labels:
    app: finops-governance
    component: schema-definition
    pipeline: infra
    team: platform
    env: prod
    cost_center: infrastructure
data:
  schema.yaml: |
    # NeuroNews FinOps Cost Allocation Labeling Schema
    # Version: 1.0
    # Effective Date: 2024-01-01
    
    required_labels:
      app:
        description: "Application or service name"
        type: "string"
        pattern: "^[a-z][a-z0-9-]*[a-z0-9]$"
        max_length: 63
        examples:
          - "neuronews-api"
          - "kafka-connect"
          - "spark-operator"
          - "prometheus"
        
      component:
        description: "Component type within the application"
        type: "string" 
        pattern: "^[a-z][a-z0-9-]*[a-z0-9]$"
        max_length: 63
        examples:
          - "backend"
          - "frontend"
          - "database"
          - "cache"
          - "message-broker"
          - "etl-job"
          - "ml-inference"
          - "metrics-collector"
        
      pipeline:
        description: "Data pipeline or business function"
        type: "enum"
        required: true
        values:
          - "ingest"     # Data ingestion and collection
          - "transform"  # Data transformation and processing
          - "dbt"        # DBT models and transformations
          - "api"        # API services and endpoints
          - "rag"        # RAG and ML inference
          - "monitoring" # Observability and monitoring
          - "infra"      # Infrastructure and platform services
        examples:
          - "ingest"     # Kafka, connectors, scrapers
          - "transform"  # Spark jobs, ETL pipelines
          - "api"        # REST APIs, GraphQL services
          - "rag"        # LLM inference, embeddings
        
      team:
        description: "Owning team responsible for the workload"
        type: "string"
        pattern: "^[a-z][a-z0-9-]*[a-z0-9]$"
        max_length: 63
        examples:
          - "neuronews"
          - "data-engineering"
          - "ml-engineering"
          - "platform"
          - "devops"
          - "security"
        
      env:
        description: "Environment designation"
        type: "enum"
        required: true
        values:
          - "dev"        # Development environment
          - "staging"    # Staging/testing environment
          - "prod"       # Production environment
          - "test"       # Automated testing environment
        examples:
          - "prod"       # Production workloads
          - "staging"    # Pre-production testing
        
      cost_center:
        description: "Business cost center for chargeback"
        type: "string"
        pattern: "^[a-z][a-z0-9-]*[a-z0-9]$"
        max_length: 63
        examples:
          - "product"           # Product development costs
          - "data-platform"     # Data infrastructure costs  
          - "infrastructure"    # Platform infrastructure costs
          - "ml-platform"       # ML infrastructure costs
          - "security"          # Security tooling costs
    
    label_recommendations:
      version:
        description: "Application version or release tag"
        type: "string"
        pattern: "^v?[0-9]+\\.[0-9]+\\.[0-9]+(-.+)?$"
        examples:
          - "v1.2.3"
          - "1.0.0-beta"
        
      tier:
        description: "Service tier for SLA and priority"
        type: "enum"
        values:
          - "critical"   # Mission-critical services
          - "high"       # High availability services  
          - "medium"     # Standard services
          - "low"        # Development/testing services
        
      data_classification:
        description: "Data sensitivity classification"
        type: "enum"
        values:
          - "public"     # Public data
          - "internal"   # Internal use only
          - "sensitive"  # Sensitive business data
          - "restricted" # Highly restricted data
    
    governance_rules:
      enforcement:
        method: "kyverno"
        policies:
          - "require-finops-labels"
          - "validate-finops-label-values"
          - "generate-missing-finops-labels"
      
      exemptions:
        namespaces:
          - "kube-system"
          - "kube-public"
          - "kube-node-lease"
          - "kyverno"
          - "cert-manager"
        resources:
          - "system:*"
      
      cost_allocation:
        dimensions:
          - "team"
          - "cost_center"
          - "pipeline"
          - "env"
        aggregation_levels:
          - "namespace"
          - "cluster"
          - "region"
        
    migration_strategy:
      phase1:
        description: "Deploy Kyverno policies in warn mode"
        duration: "2 weeks"
        actions:
          - "Install Kyverno policies"
          - "Monitor policy violations"
          - "Generate compliance reports"
      
      phase2:
        description: "Apply labels to existing workloads"
        duration: "2 weeks"
        actions:
          - "Apply Kustomize overlays"
          - "Patch existing resources"
          - "Validate label coverage"
      
      phase3:
        description: "Enforce policies in production"
        duration: "1 week"
        actions:
          - "Switch to enforce mode"
          - "Monitor for policy blocks"
          - "Handle exemption requests"
