version: 2

sources:
  - name: raw_bronze
    description: "External raw/bronze files produced by data pipelines (JSONL/Parquet)"
    schema: main
    
    tables:
      - name: raw__news
        description: "Raw news articles scraped by the pipeline, stored as Parquet files"
        meta:
          file_format: parquet
          file_pattern: "/workspaces/NeuroNews/data/bronze/news/**/*.parquet"
        loaded_at_field: scraped_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        columns:
          - name: id
            description: "Unique article identifier"
            tests:
              - not_null
              - unique
          - name: title
            description: "Article title/headline"
            tests:
              - not_null
          - name: content
            description: "Full article text content"
            tests:
              - not_null
          - name: url
            description: "Source URL of the article"
            tests:
              - not_null
              - unique
          - name: source
            description: "News source/publication"
            tests:
              - not_null
          - name: published_at
            description: "When the article was originally published"
          - name: scraped_at
            description: "When the article was scraped by our pipeline"
            tests:
              - not_null
          - name: language
            description: "Detected language of the article"
          - name: category
            description: "Article category/topic"
          - name: author
            description: "Article author"
          - name: created_at
            description: "Record creation timestamp"
            tests:
              - not_null
          - name: updated_at
            description: "Record last update timestamp"
            tests:
              - not_null

      - name: raw__entities
        description: "Extracted entities from articles (NER results) stored as JSONL files"
        meta:
          file_format: jsonl
          file_pattern: "/workspaces/NeuroNews/data/bronze/entities/**/*.jsonl"
        loaded_at_field: extracted_at
        freshness:
          warn_after: {count: 48, period: hour}
          error_after: {count: 72, period: hour}
        columns:
          - name: article_id
            description: "Reference to the source article"
            tests:
              - not_null
          - name: entity_text
            description: "The extracted entity text"
            tests:
              - not_null
          - name: entity_type
            description: "Type of entity (PERSON, ORG, LOC, etc.)"
            tests:
              - not_null
              - accepted_values:
                  values: ['PERSON', 'ORG', 'GPE', 'LOC', 'EVENT', 'PRODUCT', 'WORK_OF_ART', 'LAW', 'LANGUAGE', 'DATE', 'TIME', 'PERCENT', 'MONEY', 'QUANTITY', 'ORDINAL', 'CARDINAL']
          - name: confidence_score
            description: "Entity extraction confidence score (0-1)"
            tests:
              - not_null
              - accepted_range:
                  min_value: 0
                  max_value: 1
          - name: start_char
            description: "Start character position in text"
          - name: end_char
            description: "End character position in text"
          - name: extracted_at
            description: "When the entity was extracted"
            tests:
              - not_null
          - name: created_at
            description: "Record creation timestamp"
            tests:
              - not_null

      - name: raw__sources
        description: "Configuration and metadata for news sources being scraped"
        meta:
          file_format: parquet
          file_pattern: "/workspaces/NeuroNews/data/bronze/sources/**/*.parquet"
        loaded_at_field: updated_at
        freshness:
          warn_after: {count: 7, period: day}
          error_after: {count: 14, period: day}
        columns:
          - name: source_id
            description: "Unique identifier for the news source"
            tests:
              - not_null
              - unique
          - name: source_name
            description: "Display name of the news source"
            tests:
              - not_null
          - name: base_url
            description: "Base URL of the news source"
            tests:
              - not_null
          - name: rss_feed_url
            description: "RSS feed URL for automated scraping"
          - name: language
            description: "Primary language of the news source"
            tests:
              - not_null
          - name: country
            description: "Country/region of the news source"
          - name: category
            description: "News category focus (tech, politics, sports, etc.)"
          - name: scraping_enabled
            description: "Whether this source is actively being scraped"
            tests:
              - not_null
              - accepted_values:
                  values: [true, false]
          - name: last_scraped_at
            description: "Last successful scrape timestamp"
          - name: created_at
            description: "Source registration timestamp"
            tests:
              - not_null
          - name: updated_at
            description: "Source configuration last update timestamp"
            tests:
              - not_null
