apiVersion: v1
kind: Service
metadata:
  name: nginx-ssl-service
  namespace: neuronews
  labels:
    app: nginx-ssl-proxy
    component: ssl-proxy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:ACCOUNT_ID:certificate/CERT_ID"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
spec:
  type: LoadBalancer
  selector:
    app: nginx-ssl-proxy
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ssl-internal
  namespace: neuronews
  labels:
    app: nginx-ssl-proxy
    component: ssl-proxy
    service-type: internal
spec:
  type: ClusterIP
  selector:
    app: nginx-ssl-proxy
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
