version: '3.8'

services:
  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.7.0
    ports:
      - "9308:9308"
    command:
      - --kafka.server=redpanda:9092
      - --web.listen-address=:9308
      - --log.level=info
      - --kafka.version=2.8.0
      - --sasl.enabled=false
      - --tls.enabled=false
      - --web.telemetry-path=/metrics
      - --topic.filter=neuronews.*
      - --group.filter=cdc_.*
    depends_on:
      - redpanda
    networks:
      - cdc-monitoring
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9308/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  redpanda:
    image: redpandadata/redpanda:v24.1.4
    command: >
      redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M
      --set redpanda.auto_create_topics_enabled=true
      --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      --rpc-addr redpanda:33145
      --advertise-rpc-addr redpanda:33145
    ports:
      - "9092:9092"
      - "9644:9644"
      - "19092:19092"
      - "18081:18081"
      - "18082:18082"
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    networks:
      - cdc-monitoring
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E '(Healthy|true)'"]
      interval: 15s
      timeout: 10s
      retries: 5

networks:
  cdc-monitoring:
    driver: bridge

volumes:
  redpanda_data:
    driver: local
