global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'neuronews-fastapi'
    static_configs:
      - targets: ['fastapi:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # CDC Observability - Kafka Consumer Lag Monitoring
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # CDC Observability - Spark Streaming Metrics
  - job_name: 'spark-cdc-driver'
    static_configs:
      - targets: ['spark-driver:4040']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # CDC Observability - Spark JMX Metrics
  - job_name: 'spark-cdc-jmx'
    static_configs:
      - targets: ['spark-driver:8090']
    scrape_interval: 30s
    scrape_timeout: 10s
