apiVersion: v1
kind: Namespace
metadata:
  name: neuronews
  labels:
    name: neuronews
    environment: production
    app: neuronews
  annotations:
    description: "Production environment for NeuroNews application"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: neuronews-quota
  namespace: neuronews
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "50"
    services: "20"
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: neuronews-limits
  namespace: neuronews
spec:
  limits:
  - default:
      cpu: "1000m"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: neuronews-network-policy
  namespace: neuronews
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - podSelector: {}
  egress:
  - {} # Allow all egress for now
