apiVersion: v1
kind: Namespace
metadata:
  name: neuronews-staging
  labels:
    environment: staging
    app: neuronews
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: neuronews-api-config
  namespace: neuronews-staging
data:
  DATABASE_URL: "postgresql://neuronews:password@postgres-service:5432/neuronews_staging"
  REDIS_URL: "redis://redis-service:6379/0"
  ENVIRONMENT: "staging"
  LOG_LEVEL: "DEBUG"
  API_VERSION: "v1"
  CORS_ORIGINS: "*"
  MAX_ARTICLES_PER_REQUEST: "100"
  RATE_LIMIT_PER_MINUTE: "100"
---
apiVersion: v1
kind: Secret
metadata:
  name: neuronews-api-secrets
  namespace: neuronews-staging
type: Opaque
data:
  JWT_SECRET: "c3RhZ2luZy1qd3Qtc2VjcmV0LWtleQ=="  # staging-jwt-secret-key (base64)
  API_KEY: "c3RhZ2luZy1hcGkta2V5"  # staging-api-key (base64)
  OPENAI_API_KEY: ""  # Add your OpenAI API key (base64 encoded)
  NEWS_API_KEY: ""   # Add your News API key (base64 encoded)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuronews-api
  namespace: neuronews-staging
  labels:
    app: neuronews-api
    version: v1
    environment: staging
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: neuronews-api
  template:
    metadata:
      labels:
        app: neuronews-api
        version: v1
        environment: staging
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: api
        image: neuronews/api:staging
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8080
          name: metrics
        env:
        - name: PORT
          value: "8000"
        - name: METRICS_PORT
          value: "8080"
        envFrom:
        - configMapRef:
            name: neuronews-api-config
        - secretRef:
            name: neuronews-api-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: neuronews-api
  namespace: neuronews-staging
  labels:
    app: neuronews-api
    environment: staging
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  - port: 8080
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: neuronews-api
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: neuronews-api-hpa
  namespace: neuronews-staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: neuronews-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: neuronews-api-netpol
  namespace: neuronews-staging
spec:
  podSelector:
    matchLabels:
      app: neuronews-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - podSelector:
        matchLabels:
          app: neuronews-dashboard
    - podSelector:
        matchLabels:
          app: neuronews-scrapers
    ports:
    - protocol: TCP
      port: 8000
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - {} # Allow all egress for external APIs
