---
# Staging Environment Inventory
all:
  children:
    kubernetes:
      hosts:
        staging-k8s-master:
          ansible_host: staging-k8s.neuronews.internal
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          kubernetes_role: master
      vars:
        kubernetes_version: "1.28.0"
        kubernetes_cluster_name: neuronews-staging
        kubernetes_namespace: neuronews-staging
        
    workers:
      hosts:
        staging-k8s-worker-1:
          ansible_host: staging-worker-1.neuronews.internal
          ansible_user: ansible
          node_labels:
            - "node-type=worker"
            - "environment=staging"
        staging-k8s-worker-2:
          ansible_host: staging-worker-2.neuronews.internal
          ansible_user: ansible
          node_labels:
            - "node-type=worker"
            - "environment=staging"
      vars:
        kubernetes_role: worker

  vars:
    # Environment configuration
    environment: staging
    domain_name: staging.neuronews.com
    
    # Application configuration
    app_replicas: 2
    app_cpu_requests: 250m
    app_cpu_limits: 500m
    app_memory_requests: 256Mi
    app_memory_limits: 512Mi
    
    # Database configuration
    database_host: staging-db.neuronews.internal
    database_port: 5432
    database_name: neuronews_staging
    
    # Redis configuration
    redis_host: staging-redis.neuronews.internal
    redis_port: 6379
    
    # Monitoring configuration
    prometheus_retention: 7d
    grafana_admin_password: "{{ vault_grafana_admin_password }}"
    
    # Security configuration
    enable_network_policies: true
    enable_pod_security_policies: true
    
    # AWS configuration
    aws_region: us-west-2
    aws_vpc_id: vpc-staging123
    aws_subnet_ids:
      - subnet-staging-1
      - subnet-staging-2
    
    # EKS configuration
    eks_cluster_name: neuronews-staging
    eks_node_group_name: staging-workers
    eks_instance_type: t3.medium
    eks_desired_capacity: 2
    eks_min_size: 1
    eks_max_size: 4
