apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus-server.monitoring.svc.cluster.local:80
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 300s
      timeInterval: 30s
  
  - name: OpenCost
    type: prometheus
    access: proxy
    orgId: 1
    url: http://opencost.opencost.svc.cluster.local:9003
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 300s
      timeInterval: 30s
      customQueryParameters: "format=prometheus"
