server:
  applicationConnectors:
    - type: http
      port: 5000
  adminConnectors:
    - type: http
      port: 5001

database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://marquez-db:5432/marquez
  user: marquez
  password: marquez

logging:
  level: INFO
  loggers:
    marquez: INFO
  appenders:
    - type: console
      logFormat: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

flyway:
  locations:
    - classpath:marquez/db/migration
  baselineOnMigrate: true

graphql:
  enabled: true

tags:
  - name: PII
    description: Contains Personally Identifiable Information
  - name: SENSITIVE
    description: Contains sensitive business data

metrics:
  frequency: 5s
