version: '3.8'

services:
  neuronews-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neuronews-go-scraper
    volumes:
      - ./output:/app/output
      - ./config.json:/app/config/config.json:ro
    environment:
      - TZ=UTC
    command: ["./neuronews-scraper", "-config", "config/config.json", "-verbose"]
    restart: unless-stopped
    
  # JavaScript-heavy scraper service
  neuronews-js-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neuronews-js-scraper
    volumes:
      - ./output:/app/output
      - ./config.json:/app/config/config.json:ro
    environment:
      - TZ=UTC
    command: ["./neuronews-scraper", "-config", "config/config.json", "-js", "-verbose"]
    restart: unless-stopped
    
  # Test scraper service
  neuronews-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neuronews-test-scraper
    volumes:
      - ./output:/app/output
    environment:
      - TZ=UTC
    command: ["./neuronews-scraper", "-test", "-verbose"]
    restart: "no"
    profiles:
      - test

volumes:
  scraper_output:
    driver: local
