apiVersion: v1
kind: Service
metadata:
  name: neuronews-api-service
  namespace: neuronews
  labels:
    app: neuronews-api
    component: backend
spec:
  selector:
    app: neuronews-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: neuronews-dashboard-service
  namespace: neuronews
  labels:
    app: neuronews-dashboard
    component: frontend
spec:
  selector:
    app: neuronews-dashboard
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: neuronews
  labels:
    app: redis
    component: cache
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: neuronews
  labels:
    app: postgres
    component: database
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  type: ClusterIP
