apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-finops-config
  namespace: monitoring
  labels:
    app: alertmanager
    component: config
    purpose: finops-alerts
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: '${SMTP_HOST:localhost:587}'
      smtp_from: '${SMTP_FROM:alerts@neuronews.io}'
      smtp_auth_username: '${SMTP_USERNAME:alerts@neuronews.io}'
      smtp_auth_password: '${SMTP_PASSWORD:}'
      slack_api_url: '${SLACK_WEBHOOK_URL:}'

    # Templates for alert formatting
    templates:
      - '/etc/alertmanager/templates/*.tmpl'

    # Route configuration
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'default'
      routes:
      
      # FinOps Budget Alerts - High Priority
      - match:
          category: finops
          impact: budget
        receiver: 'finops-budget-critical'
        group_wait: 0s
        group_interval: 5m
        repeat_interval: 4h
        routes:
        - match:
            severity: critical
          receiver: 'finops-budget-critical'
          repeat_interval: 1h
        - match:
            severity: warning
          receiver: 'finops-budget-warning'
          repeat_interval: 4h
      
      # FinOps Cost Drift Alerts
      - match:
          category: finops
          impact: cost-drift
        receiver: 'finops-cost-drift'
        group_wait: 0s
        group_interval: 10m
        repeat_interval: 6h
        routes:
        - match:
            severity: critical
          receiver: 'finops-cost-drift-critical'
          repeat_interval: 2h
      
      # Unit Economics Alerts
      - match:
          category: finops
          impact: unit-economics
        receiver: 'finops-unit-economics'
        group_wait: 30s
        group_interval: 30m
        repeat_interval: 12h
      
      # Resource Efficiency Alerts
      - match:
          category: finops
          impact: efficiency
        receiver: 'finops-efficiency'
        group_wait: 1m
        group_interval: 1h
        repeat_interval: 24h

    # Receivers (notification endpoints)
    receivers:
    
    # Default receiver
    - name: 'default'
      slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL_DEFAULT:}'
        channel: '#alerts'
        title: 'NeuroNews Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
    
    # Critical Budget Alerts - Immediate attention required
    - name: 'finops-budget-critical'
      slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL_FINOPS:}'
        channel: '#finops-critical'
        title: '🚨 CRITICAL: Budget Alert - NeuroNews'
        title_link: '{{ (index .Alerts 0).Annotations.grafana_url }}'
        text: |
          *Alert:* {{ (index .Alerts 0).Labels.alertname }}
          *Severity:* {{ (index .Alerts 0).Labels.severity | upper }}
          *Summary:* {{ (index .Alerts 0).Annotations.summary }}
          
          {{ (index .Alerts 0).Annotations.description }}
          
          *Runbook:* {{ (index .Alerts 0).Annotations.runbook_url }}
          *Dashboard:* {{ (index .Alerts 0).Annotations.grafana_url }}
        color: 'danger'
        actions:
        - type: button
          text: 'View Dashboard'
          url: '{{ (index .Alerts 0).Annotations.grafana_url }}'
        - type: button
          text: 'Runbook'
          url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
      email_configs:
      - to: '${FINOPS_EMAIL_CRITICAL:platform-team@neuronews.io}'
        subject: '🚨 CRITICAL: {{ (index .Alerts 0).Labels.alertname }} - NeuroNews'
        body: |
          Alert: {{ (index .Alerts 0).Labels.alertname }}
          Severity: {{ (index .Alerts 0).Labels.severity | upper }}
          
          {{ (index .Alerts 0).Annotations.description }}
          
          Dashboard: {{ (index .Alerts 0).Annotations.grafana_url }}
          Runbook: {{ (index .Alerts 0).Annotations.runbook_url }}
          
          This alert requires immediate attention as it indicates critical budget overruns.
    
    # Budget Warning Alerts
    - name: 'finops-budget-warning'
      slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL_FINOPS:}'
        channel: '#finops-alerts'
        title: '⚠️ Budget Alert - NeuroNews'
        title_link: '{{ (index .Alerts 0).Annotations.grafana_url }}'
        text: |
          *Alert:* {{ (index .Alerts 0).Labels.alertname }}
          *Summary:* {{ (index .Alerts 0).Annotations.summary }}
          
          {{ (index .Alerts 0).Annotations.description }}
        color: 'warning'
        actions:
        - type: button
          text: 'View Dashboard'
          url: '{{ (index .Alerts 0).Annotations.grafana_url }}'
    
    # Cost Drift Critical Alerts
    - name: 'finops-cost-drift-critical'
      slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL_FINOPS:}'
        channel: '#finops-critical'
        title: '🔥 CRITICAL: Cost Spike Detected - NeuroNews'
        text: |
          *Alert:* {{ (index .Alerts 0).Labels.alertname }}
          *Summary:* {{ (index .Alerts 0).Annotations.summary }}
          
          {{ (index .Alerts 0).Annotations.description }}
        color: 'danger'
      email_configs:
      - to: '${FINOPS_EMAIL_CRITICAL:platform-team@neuronews.io}'
        subject: '🔥 CRITICAL: Cost Spike - {{ (index .Alerts 0).Labels.alertname }}'
        body: |
          {{ (index .Alerts 0).Annotations.description }}
          
          This alert indicates a significant cost increase that requires immediate investigation.
    
    # Cost Drift Alerts
    - name: 'finops-cost-drift'
      slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL_FINOPS:}'
        channel: '#finops-alerts'
        title: '📈 Cost Drift Alert - NeuroNews'
        text: |
          *Alert:* {{ (index .Alerts 0).Labels.alertname }}
          *Summary:* {{ (index .Alerts 0).Annotations.summary }}
          
          {{ (index .Alerts 0).Annotations.description }}
        color: 'warning'
    
    # Unit Economics Alerts
    - name: 'finops-unit-economics'
      slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL_FINOPS:}'
        channel: '#finops-unit-economics'
        title: '💰 Unit Economics Alert - NeuroNews'
        text: |
          *Alert:* {{ (index .Alerts 0).Labels.alertname }}
          *Summary:* {{ (index .Alerts 0).Annotations.summary }}
          
          {{ (index .Alerts 0).Annotations.description }}
        color: 'warning'
        actions:
        - type: button
          text: 'Unit Economics Dashboard'
          url: 'http://grafana.monitoring.svc.cluster.local:3000/d/unit-economics-001/unit-economics-cost-per-outcome'
    
    # Resource Efficiency Alerts
    - name: 'finops-efficiency'
      slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL_FINOPS:}'
        channel: '#finops-efficiency'
        title: '⚡ Efficiency Alert - NeuroNews'
        text: |
          *Alert:* {{ (index .Alerts 0).Labels.alertname }}
          *Summary:* {{ (index .Alerts 0).Annotations.summary }}
          
          {{ (index .Alerts 0).Annotations.description }}
        color: 'warning'

    # Inhibition rules - prevent lower severity alerts when higher severity ones are firing
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'cluster', 'service']
    - source_match:
        alertname: 'FinOpsMonthlyBudgetCriticalBreach'
      target_match:
        alertname: 'FinOpsMonthlyBudgetBreach'
      equal: ['cluster']
    - source_match:
        alertname: 'FinOpsCostDriftCritical'
      target_match:
        alertname: 'FinOpsCostDriftWoW'
      equal: ['cluster']
