apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    component: metrics-collector
    pipeline: monitoring
    team: platform
    env: prod
    cost_center: infrastructure
spec:
  template:
    metadata:
      labels:
        app: prometheus
        component: metrics-collector
        pipeline: monitoring
        team: platform
        env: prod
        cost_center: infrastructure

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    component: visualization
    pipeline: monitoring
    team: platform
    env: prod
    cost_center: infrastructure
spec:
  template:
    metadata:
      labels:
        app: grafana
        component: visualization
        pipeline: monitoring
        team: platform
        env: prod
        cost_center: infrastructure

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: monitoring
  labels:
    app: kafka-exporter
    component: metrics-exporter
    pipeline: monitoring
    team: platform
    env: prod
    cost_center: infrastructure
spec:
  template:
    metadata:
      labels:
        app: kafka-exporter
        component: metrics-exporter
        pipeline: monitoring
        team: platform
        env: prod
        cost_center: infrastructure

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencost
  namespace: opencost
  labels:
    app: opencost
    component: cost-analyzer
    pipeline: monitoring
    team: platform
    env: prod
    cost_center: infrastructure
spec:
  template:
    metadata:
      labels:
        app: opencost
        component: cost-analyzer
        pipeline: monitoring
        team: platform
        env: prod
        cost_center: infrastructure
