name: Airflow DAG Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dag-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install Apache Airflow
        run: |
          pip install apache-airflow==2.8.1
      - name: Install project requirements
        run: |
          pip install -r airflow/requirements.txt || true
          pip install -r requirements.txt || true
          pip install pytest
      - name: Run DAG import/unit tests
        run: pytest -q tests/dags
