# name: S3 Storage Tests

# on:
#   push:
#     branches: [ main ]
#     paths:
#       - 'src/database/s3_storage.py'
#       - 'tests/database/test_s3_storage.py'
#   pull_request:
#     branches: [ main ]
#     paths:
#       - 'src/database/s3_storage.py'
#       - 'tests/database/test_s3_storage.py'

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test-key
      AWS_SECRET_ACCESS_KEY: test-secret
      MOTO_S3_CUSTOM_ENDPOINTS: http://localhost:5000
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov
    
    - name: Run tests with mocked S3
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        pytest tests/database/test_s3_storage.py -v --cov=src/database