name: S3 Storage Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/database/s3_storage.py'
      - 'tests/database/test_s3_storage.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/database/s3_storage.py'
      - 'tests/database/test_s3_storage.py'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Run tests
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        S3_BUCKET: neuronews-raw-articles-test
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        pytest tests/database/test_s3_storage.py -v --cov=src/database