name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      gremlin-server:
        image: tinkerpop/gremlin-server:3.6.2
        ports:
          - 8182:8182
        env:
          GREMLIN_SERVER_PORT: 8182
          JAVA_OPTS: "-Xmx1024m"
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-dev \
          python3-setuptools \
          build-essential \
          gcc \
          jq \
          netcat-openbsd \
          libffi-dev \
          libssl-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install aiohttp==3.8.1  # Install aiohttp first
        python -m pip install gremlinpython==3.6.2
        python -m pip install -r requirements.txt

    - name: Verify Dependencies
      run: |
        echo "Checking installed packages:"
        pip list
        echo "\nVerifying gremlinpython installation:"
        python -c "import gremlinpython; print(f'gremlinpython version: {gremlinpython.__version__}')"
        python -c "from gremlin_python.driver.driver_remote_connection import DriverRemoteConnection; print('gremlin_python imports working')"
        echo "\nVerifying aiohttp installation:"
        python -c "import aiohttp; print(f'aiohttp version: {aiohttp.__version__}')"

    - name: Debug Container Status
      run: |
        echo "Docker version:"
        docker version
        
        echo "\nDocker info:"
        docker info
        
        echo "\nListing all containers:"
        docker ps -a
        
        echo "\nContainer details:"
        CONTAINER_ID=$(docker ps -q -f "ancestor=tinkerpop/gremlin-server:3.6.2" || \
                      docker ps -q -f "name=gremlin-server" || \
                      docker ps -q -f "name=*_gremlin-server_*")
        if [ -n "$CONTAINER_ID" ]; then
          echo "Found container: $CONTAINER_ID"
          echo "\nContainer logs:"
          docker logs $CONTAINER_ID
          echo "\nContainer inspection:"
          docker inspect $CONTAINER_ID | jq '.[0].State'
          echo "\nContainer network settings:"
          docker inspect $CONTAINER_ID | jq '.[0].NetworkSettings'
        else
          echo "No Gremlin server container found"
        fi

    - name: Monitor Gremlin Server
      run: |
        chmod +x .github/workflows/monitor-container.sh
        sudo ./.github/workflows/monitor-container.sh

    - name: Run base pipeline tests
      run: |
        python -m pytest tests/test_base_pipelines.py -v

    - name: Run base NLP tests
      run: |
        python -m pytest tests/test_base_nlp.py -v

    - name: Run unit tests
      run: |
        python -m pytest tests/ -v --ignore=tests/nlp/test_sentiment.py --ignore=tests/integration

    - name: Run integration tests
      env:
        NEPTUNE_ENDPOINT: localhost
        GREMLIN_SERVER_URL: ws://localhost:8182/gremlin
      run: |
        python -m pytest tests/integration/test_graph_integration.py -v

  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
    - name: Initialize Terraform
      run: |
        cd deployment/terraform
        terraform init -backend=false
      
    - name: Validate Terraform Configuration
      run: |
        cd deployment/terraform
        terraform validate