name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov coverage pytest-html boto3

    - name: Run base pipeline tests
      run: |
        python -m pytest tests/test_base_pipelines.py -v --cov=src.scraper.pipelines --cov-report=term-missing

    - name: Run all tests
      run: |
        python -m pytest tests/ -v --cov=src --cov-report=html
        
    - name: Upload coverage report
      uses: actions/upload-pages-artifact@v3
      with:
        path: htmlcov

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        artifact_name: github-pages

  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
    - name: Initialize Terraform
      run: |
        cd deployment/terraform
        terraform init -backend=false
      
    - name: Validate Terraform Configuration
      run: |
        cd deployment/terraform
        terraform validate