name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run base pipeline tests
      run: |
        python -m pytest tests/test_base_pipelines.py -v

    - name: Run base NLP tests
      run: |
        python -m pytest tests/test_base_nlp.py -v

    - name: Run all tests
      run: |
        python -m pytest tests/ -v --ignore=tests/nlp/test_sentiment.py

  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
    - name: Initialize Terraform
      run: |
        cd deployment/terraform
        terraform init -backend=false
      
    - name: Validate Terraform Configuration
      run: |
        cd deployment/terraform
        terraform validate